import pandas as pd

def create_cats():
    primary_cats = ['Bakery',
    'Baking',
    'Beauty and Grooming',
    'Beverages',
    'Breakfast and Cereal',
    'Candy and Gum',
    'Canned Goods and Soups',
    'Condiments, Sauces and Seasonings',
    'Dairy',
    'Deli',
    'Frozen Foods',
    'Grains and Pasta',
    'Household essentials',
    'Meat, Seafood and Poultry',
    'Pets',
    'Produce',
    'Snacks, Cookies and Chips']

    secondary_cats = ['Fruits',
    'Bread',
    'Milk',
    'Vegetables',
    'Cheese',
    'Eggs',
    'Juice',
    'Cereal',
    'Sauces',
    'Chips and Bagged Popcorn',
    'Pasta',
    'Yogurt',
    'Bacon and Sausages',
    'Soft Drinks',
    'Paper Goods',
    'Frozen Vegetables',
    'Bath and Body',
    'Crackers',
    'Chocolate',
    'Cookies',
    'Pizza',
    'Water',
    'Condiments',
    'Soups',
    'Canned Vegetables',
    'Plastic Goods',
    'Coffee',
    'Frozen Dinners and Meals',
    'Mixes',
    'Dips and Spreads',
    'Deli Meat',
    'Salad Dressings',
    'Hair Care',
    'Nut Spread and Butter',
    'Beef',
    'Hot Dogs',
    'Meat',
    'Frozen Breakfast Food',
    'Poultry',
    'Syrups and Sweeteners',
    'Jam, Jelly and Preserves',
    'Dog',
    'Tuna and Seafood',
    'Frozen Rolls and Wraps',
    'Pork',
    'Frozen Seafood',
    'Cat',
    'Seafood',
    'Meat and Poultry',
    'Jerky',
    'Outdoor Grilling']
    return primary_cats, secondary_cats

if __name__ == '__main__':
    primary_cats, secondary_cats = create_cats()
    
    for prim_cat in primary_cats:
        print prim_cat
        # create csv. with all device ids for that primary cat
